import './globals.css';

import PageHeader from './PageHeader';
import PageFooter from './PageFooter';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PageHeader />
        {children}
        <PageFooter />
      </body>
    </html>
  );
}
