import { montserrat, josefin_sans } from './fonts';

import './globals.css';
import './styles.scss';

import PageHeader from './PageHeader';
import PageFooter from './PageFooter';

export const metadata = {
  title: 'Andrew Jensen-Battaglia',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${josefin_sans.variable}`}
    >
      <body>
        <PageHeader />
        {children}
        <PageFooter />
      </body>
    </html>
  );
}
